name: Build Linux x86_64 and ARM64

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  setup-release-info:
    name: Setup Release Info
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.version.outputs.version }}
      release-tag-name: ${{ steps.tag.outputs.tag-name }}
      release-title: ${{ steps.title.outputs.title }}
      is-prerelease: ${{ steps.prerelease.outputs.prerelease }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract version from CMakeLists.txt
        id: version
        run: echo "version=$(grep -oP 'project\(TelegramBotApi VERSION \K[\d.]+' CMakeLists.txt)" >> $GITHUB_OUTPUT
      - name: Determine Tag Name
        id: tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "tag-name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag-name=manual-${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi
      - name: Determine Release Title
        id: title
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "title=${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "title=manual-${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi
      - name: Determine Prerelease
        id: prerelease
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "prerelease=false" >> $GITHUB_OUTPUT
          else
            echo "prerelease=true" >> $GITHUB_OUTPUT
          fi
---
  build-x86_64:
    name: Build for Linux x86_64 (Alpine Static)
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install build essentials for Alpine
        run: |
          apk update
          apk add --no-cache \
            build-base \
            cmake \
            gperf \
            zlib-static \
            openssl-static
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build x86_64
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_FLAGS=-static \
                -DCMAKE_CXX_FLAGS=-static \
                ..
          cmake --build . --target install
      - name: Rename artifact
        run: mv build/telegram-bot-api build/telegram-bot-api-linux-x86_64
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: telegram-bot-api-x86_64
          path: build/telegram-bot-api-linux-x86_64
---
  build-arm64:
    name: Build for Linux ARM64 (Alpine Static)
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install dependencies for Alpine on ARM64
        run: |
          apk update
          apk add --no-cache \
            build-base \
            cmake \
            gperf \
            zlib-static \
            openssl-static \
            binutils-aarch64-linux-gnu \
            musl-dev
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build ARM64
        run: |
          mkdir -p build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_CROSSCOMPILING=True \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -DCMAKE_C_FLAGS="-static" \
            -DCMAKE_CXX_FLAGS="-static" \
            -DCMAKE_PREFIX_PATH=/usr/lib/aarch64-linux-gnu \
            ..
          cmake --build .
      - name: Rename artifact
        run: mv build/telegram-bot-api build/telegram-bot-api-linux-arm64
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: telegram-bot-api-arm64
          path: build/telegram-bot-api-linux-arm64
---
  create-release:
    name: Create Release
    needs: [setup-release-info, build-x86_64, build-arm64]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.setup-release-info.outputs.release-title }}
          tag_name: ${{ needs.setup-release-info.outputs.release-tag-name }}
          prerelease: ${{ needs.setup-release-info.outputs.is-prerelease }}
          files: |
            telegram-bot-api-x86_64/telegram-bot-api-linux-x86_64
            telegram-bot-api-arm64/telegram-bot-api-linux-arm64
          generate_release_notes: true
